_BASE_: "Base-SLRESNET-FCOS.yaml"
MODEL:
  SLRESNETS:
    NORM: "BN"
    DEPTH: 50
    WIDTH_MULT: 0.50
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
SOLVER:
  CHECKPOINT_PERIOD: 160000
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 4
  BASE_LR: 0.005  # Note that RetinaNet uses a different default learning rate
  STEPS: (240000, 320000)
  MAX_ITER: 360000
